### ISSUE TITLE
Add GitHub Actions CI to compile the frontend

### ISSUE THREAD

**Issue by epiccurious** [wild-kard/arctica-frontend#1]
Create a [YAML file](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#using-the-nodejs-starter-workflow) that:
- triggers on every commit to master branch and pull request to master branch
- installs dependencies with `npm install` or `npm ci`
- compiles the frontend with `npm run build`
- fails the text with any non-zero exits (`exit 1`)

**Comment by wild-kard** [comment]
Resolved https://github.com/wild-kard/arctica-frontend/pull/3
